version: '3'

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_DB=postgres
          - POSTGRES_HOST_AUTH_METHOD=md5
        ports:
          - 5432:5432
        volumes:
          - ./postgres/data:/var/lib/postgresql/data
          - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
          - 8080:8080

    package-management:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: package-management
        restart: always
        environment:
          - POSTGRES_URL=postgres
          - POSTGRES_USER=python
          - POSTGRES_PW=python
          - POSTGRES_DB=package-management
          - TIMEOUT_DB_INIT=15
          - APP_VERSION=1.0.0
          - APP_ENV=DEBUG
        ports:
          - 80:5000
        depends_on:
          - postgres
